config/routes.rb
Rails.application.routes.draw do

  resources :tickets
  resources :tic_types
  devise_for :controllers
  namespace :admin do
    resources :users
    resources :categories
    resources :registers

    resources :tickets do
      member do
        patch :change_status
      end
    end

    root to: "users#index"
  end

  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :registers do
    collection do
      match 'search' => 'registers#compare', via: [:get, :post], as: :search
    end
  end
  # resources :registers , only: [:create]

  root 'welcome#index'
  get "/About", to: "welcome#about"
  get "/Contact", to: "welcome#contact"
  get "/Index", to: "welcome#index"
  get "/Compare", to: "registers#compare"
  get "/Console", to: "welcome#console"
  get "/mobile", to: "welcome#mobile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/register.rb
class Register < ApplicationRecord

	include AASM 

	belongs_to :user
	belongs_to :category

	validates :monto, presence: true
	validates :medida, presence: true
	validates :costos_adicionales, presence: true
	validates :fecha, presence: true
	validates :descripcion, presence: true, length: { minimum: 10}	
	before_create :set_costos_adicionales

	scope :activos, ->{ where(state:"active") }

	scope :ultimos, ->{ order("created_at DESC")}

	aasm column: "state" do
		state :active, initial: true
		state :unactive

		event :actived do
			transitions from: :unactive, to: :active
		end

		event :unactived do
			transitions from: :active, to: :unactive
		end

	end

	UNRANSACKABLE_ATTRIBUTES = ["id", "updated_at", "created_at", "user", "Category", "state","cantidad_medida", "user_id"]

	def self.ransackable_attributes auth_object = nil
		(column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
	end

	private

	def set_costos_adicionales
		self.costos_adicionales = 0
	end
end

app/controllers/admin/registers_controller.rb
module Admin
  class RegistersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Register.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Register.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_register, except: [:index,:new,:create,:compare]

	def index
		@search = current_user.registers.search(params[:q])
		@registers = @search.result(distinct: true).paginate(page: params[:page], per_page: 5).ultimos.activos
		@search.build_condition if @search.conditions.empty?

		respond_to do |format|
			format.html
			format.json
			format.pdf {render template: 'registers/reporte', pdf: 'Reporte', layout: 'pdf.html'}
		end


	end
		# if params[:search]
		# 	@registers = current_user.registers.where('monto LIKE ?', "%#{params[:search]}%").paginate(page: params[:page], per_page: 10).publicados.ultimos
		# else
		# 	@registers = current_user.registers.paginate(page: params[:page], per_page: 10).publicados.ultimos
		# end
		#@registers = current_user.registers.where(state:"active")
	def search
  		compare
  		render :index
	end
	def show
		#Register.where.not("activo = false")
	end
	def new
		@register = current_user.registers.new
	end
	def create
		@register = current_user.registers.new(register_params)
		if @register.save
			redirect_to @register
		else
			render :new
		end
	end
	def edit

	end
	def destroy

		@register.destroy
		redirect_to registers_path
	end
	def update
		if @register.update(register_params)
			redirect_to registers_path
		else
			render :edit
		end
	end

	def compare

		# rango1 = params[:desde]
		# rango2 = params[:hasta]
		@searchCompare = current_user.registers.search(params[:q])
		if params[:q]

			@registers = @searchCompare.result(distinct: true).order(fecha: :asc).paginate(page: params[:page], per_page: 5)
		end

	end

	private

	def set_register
		@register = Register.find(params[:id])
	end

	def register_params
		params.require(:register).permit(:monto,:medida,:fecha,:descripcion,:costos_adicionales,:category_id,:search,:consumo)
	end
end

app/views/registers/_condition_fields.html.erb
<div class="field">
	<%= f.attribute_fields do |a| %>
		<%= a.attribute_select({associations: [:category]},{class:'form-control form-size d-inline custom-select'}) %>             
	<% end %>                                           
	<%= f.predicate_select({only: [:cont, :lteq, :gteq]},{class:'d-inline form-inline form-size form-control custom-select'})%>
	<%= f .value_fields do |v| %>                          
		<%= v.text_field :value, class:"form-control d-inline form-size form-inline" %>   
	<%end%>
	<%= link_to "Remover", '#', class:"remove_fields btn btn-danger"%>
</div> 

app/views/registers/_form.html.erb
<%= form_for(@register, remote: true) do |f|%>
<% @register.errors.full_messages.each do |mesage|%>
<div class="container" style="color: red">
	* <%= mesage %>
</div>
<%end%>

<div class="space-top-lg rounded-div p-3" style="background-color: white; width: 95%; margin: 0 auto;">
	<div class="container-form form-group ">

		<label>Categorías</label><br>
		<%= f.select(:category_id, [['Agua', 1],['Luz',2],['Teléfono',3],['Gas',4]], {}, { :class=> 'form-control', id: "selectCategories", onchange: "categories()"}) %>

		<label class="space-top-md">Medida</label>
		<%= f.text_field :medida, placeholder: "Medida", class: "form-control d-inline form-inline form-size", id:"medidaRegister", value: "m3", disabled: true%>

		<label class="space-top ml-5">Consumo</label>
		<%= f.text_field :consumo, class: "form-control d-inline form-size"%><br>

		<label class="space-top">Monto</label>
		<%= f.number_field :monto, placeholder: "$", class: "form-control"%>

		<label class="space-top">Costos adicionales</label>
		<%= f.number_field :costos_adicionales, placeholder: "Costos adicionales", class: "form-control", value: 0 %>

		<label class="space-top">Fecha</label>
		<%= f.date_field :fecha, placeholder: "Tipo", class: "form-control input-daterange"%>

		<label class="space-top">Descripción</label>
		<%= f.text_area :descripcion, placeholder: "Descripción", class: "form-control space-top", style: "height: 100px"%>
		<%= f.submit "Aceptar", class: "btn btn-success form-control space-top", style: "width: 200px; margin-top: 10px;"%>

		<%end%>
	</div>
</div>

<script>
    $('.input-daterange').datepicker({
        format: 'yyyy-mm-dd'
    });
</script>

app/views/registers/_show.html.erb
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document" style="width: 800px" >
		<div class="modal-content mx-auto justify-content-center rounded-div">
			<div class="modal-header bg-dark text-white">
				<h4 class="modal-title p-2" id="exampleModalLongTitle">Registro</h4>
				<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body p-4">

				<div class="container rounded-div" style="background-color: #fff;">
					<% if @register.category.name.eql?('Agua') %>
						<h4 class="modal-title" id="exampleModalLongTitle"> Categoría del registro: <i class="fas fa-tint ml-2 text-primary" data-toggle="tooltip" title="Agua" style="font-size: 30px;"></i></h4>
					<% elsif @register.category.name.eql?('Luz') %>
						<h4 class="modal-title" id="exampleModalLongTitle">Categoría del registro: <i class="fas fa-lightbulb ml-2" data-toggle="tooltip" title="Luz" style="color: #F9E237; font-size: 30px;"></i></h4>
					<% elsif @register.category.name.eql?('Teléfono') %>
						<h4 class="modal-title" id="exampleModalLongTitle">Categoría del registro: <i class="fas fa-phone ml-2" data-toggle="tooltip" title="Teléfono" style="font-size: 30px; color: #72B441;"></i></h4>
					<% else %>
						<h4 class="modal-title" id="exampleModalLongTitle">Categoría del registro: <i class="fas fa-burn ml-2" data-toggle="tooltip" title="Gas" style="color: #F48039; font-size: 30px;"></i></h4>
					<% end %>
					<hr>
					<h4>Fecha del registro: <%= @register.fecha.strftime("%m/%d/%Y") %></h4>
					<hr>
					<h4>Monto del registro: <%= @register.monto %></h4>
					<hr>
					<% if @register.consumo > 0 %>
						<h4>Consumo: <%= @register.consumo %> - <%= @register.medida %> </h4>
						<hr>
					<% end %>
					<h4>Costos adicionales: <%= @register.costos_adicionales %></h4>
					<hr>
					<h4>Descripción: </h4>
					<h5 class="p-2"> <%= @register.descripcion%> </h5>
				</div>

			</div>
		</div>
	</div>

app/views/registers/compare.html.erb
<%= javascript_include_tag "highcharts", "chartkick" %>

    <div class="rounded-div mt-5 p-1" style="background-color: white; width: 95%; margin: 0 auto;">
        <h2 class="text-center mt-5">Comparar registros </h2>


        <%= search_form_for @searchCompare, url: search_registers_path,
        html: { method: :post } do |f| %>
        <div class="input-group space-top-xl">
            <div class="row align-items-center container-fluid">
                <div class="col-sm-6 d-inline mb-4">
                    <div class="container">
                    <%= f.text_field :fecha_gteq, class:" input-daterange2 input-sm d-inline font-lg text-center", placeholder: "Fecha mayor o igual a "%>
                    </div>
                </div>
                <div class="col-sm-6 d-inline mb-4" >
                    <div class="container">
                    <%= f.text_field :fecha_lteq, class:"input-daterange input-sm d-inline font-lg text-center", placeholder: "Fecha menor o igual a "%>
                    </div>
                </div>
                <div class="col-md-auto d-inline mt-3" style="margin: 0 auto;">
                    <button type="submit" class="btn btn-success">Buscar</button>
                </div>
            </div>

        </div>
        <hr/>

        <%end%>

    <%if @registers %>

    <div class="table-responsive p-3 rounded-div mt-4" style="background-color: white; width: 95%; margin: 0 auto;">

    <%@registers.each do |register|%>
    <table class="table space-top-lg margin-registers hoverable" style="border: 2px solid rgba(159, 150, 148, 0.6);">
        <thead class="bg-dark text-white font-weight-bold">
            <tr>
                <th class="text-center font-md font-weight-bold" style="width: 15%">Tipo</th>
                <th class="text-center font-md font-weight-bold" style="width: 15%">Valor</th>
                <th class="text-center font-md font-weight-bold" style="width: 15%">Fecha</th>
                <th class="text-center font-md font-weight-bold" style="width: 15%">Costos adicionales</th>
                <th class="text-center font-md" colspan="3">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center font-md"><%= register.category.name%></td>
                <td class="text-center font-md"><%= register.monto%> $</td>
                <td class="text-center font-md"><%= register.fecha%></td>
                <td class="text-center font-md"><%= register.costos_adicionales%> $</td>
                <td class="text-center font-md"><%= link_to register, class:"no-decoration", remote: true do %>
                    <i class="fa fa-eye "></i>
                    Ver registro
                    <% end %></td>
                    <td class="text-center font-md"><%= link_to edit_register_path(register), class:"no-decoration" do%>
                        <i class="fa fa-edit"></i>
                        Editar
                        <%end%></td>
                        <td class="text-center font-md"><%= link_to register, method: :delete, remote: true, class:"no-decoration", data: { confirm: '¿Estás seguro?', } do %>
                            <i class="fa fa-trash"></i>
                            Eliminar
                            <%end%></td>

                        </tr>
                        <%end%>
                    </tbody>

                </table>
            </div>

    <%if @registers.count > 0%>
        <h2 class="text-center mt-5"> Gráfica comparativa </h2>
        <div class="container mt-2">
            <%= line_chart @registers.group(:fecha).group_by_month(:fecha).sum(:monto), xtitle: "Fecha", ytitle: "Monto", download: true %>
        </div>
    <%end%>
 <%end%>

</div>


<script>
    $('.input-daterange').datepicker({
        format: 'yyyy-mm-dd'
    });

    $('.input-daterange2').datepicker({
        format: 'yyyy-mm-dd'
    });
</script>

app/views/registers/edit.html.erb
<div class="space-top-md rounded-div p-4" style="background-color: white; width: 95%; margin: 0 auto;">
	<h1>Editar registro</h1>

	<%= render "form" %>
</div>

app/views/registers/index.html.erb
<div class="space-top-lg rounded-div p-3" style="border: 2px solid rgba(159, 150, 148, 0.6); background-color: white; width: 95%; margin: 0 auto;">
	<h2 style="margin-bottom: 50px">Registros</h2>
	<h4>Buscar registros</h4>
	<%= search_form_for @search do |f| %>
	<%= f.condition_fields do |c| %>
	<%= render "condition_fields", f: c%>
	<%end %>
	<p class="space-top btn">
		<%= link_to_add_fields "Añadir condición de busqueda", f, :condition%>
	</p>
	<div class="actions">
		<%= f.submit class:"btn btn-success" %>
		<%= link_to "Reiniciar búsqueda", registers_path, class:"btn btn-info" %>
	</div>
	<% end %>
</div>

<div class="table-responsive p-3 rounded-div mt-4" style="background-color: white; width: 95%; margin: 0 auto;">

	<%= link_to "Crear nuevo registro", new_register_path, class:"btn btn-success btnColor btn-md hoverable font-sm"%></%>

	<%@registers.each do |register|%>
	<table class="table space-top-lg margin-registers hoverable" style="border: 2px solid rgba(159, 150, 148, 0.6);">
		<thead class="bg-dark text-white font-weight-bold">
			<tr>
				<th class="text-center font-md font-weight-bold" style="width: 15%">Tipo</th>
				<th class="text-center font-md font-weight-bold" style="width: 15%">Valor</th>
				<th class="text-center font-md font-weight-bold" style="width: 15%">Fecha</th>
				<th class="text-center font-md font-weight-bold" style="width: 15%">Costos adicionales</th>
				<th class="text-center font-md" colspan="3">Acciones</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td class="text-center font-md"><%= register.category.name%></td>
				<td class="text-center font-md"><%= register.monto%> $</td>
				<td class="text-center font-md"><%= register.fecha%></td>
				<td class="text-center font-md"><%= register.costos_adicionales%> $</td>
				<td class="text-center font-md"><%= link_to register, class:"no-decoration", remote: true do %>
					<i class="fa fa-eye "></i>
					Ver registro
					<% end %></td>
					<td class="text-center font-md"><%= link_to edit_register_path(register), class:"no-decoration" do%>
						<i class="fa fa-edit"></i>
						Editar
						<%end%></td>
						<td class="text-center font-md"><%= link_to register, method: :delete, remote: true, class:"no-decoration", data: { confirm: '¿Estás seguro?', } do %>
							<i class="fa fa-trash"></i>
							Eliminar
							<%end%></td>

						</tr>
						<%end%>
					</tbody>

				</table>

				<div class="mt-4 mb-4">
					<%= link_to '' do %>
					<a href="" class="no-decoration font-md" onclick="report()"><i class="fas fa-file-pdf"></i> Generar PDF</a>

					<%end%>
				</div>

				<div class="container space-top-md">
					<%= will_paginate @registers, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer, class: "paginacion" %>
				</div>

			</div>
			<script>

				function report(){
					var str = window.location.href;
					var reportUrl = str.replace('registers', 'registers.pdf');
					window.location.href = reportUrl;
				}


			</script>

			<script>


				jQuery(function() {
					$('form').on('click', '.remove_fields', function(event) {
						$(this).closest('.field').remove();
						event.preventDefault();
					});

					$('form').on('click', '.add_fields', function(event) {
						const time = new Date().getTime();
						const regexp = new RegExp($(this).data('id'), 'g');

						$(this).closest('p').before($(this).data('fields').replace(regexp, time));
						event.preventDefault();
					});
				});



			</script>

app/views/registers/new.html.erb
<div class="space-top-md rounded-div p-4" style="background-color: white; width: 95%; margin: 0 auto;">
  <h1>Crear registro</h1>

  <%= render "form" %>
</div>

app/views/registers/reporte.pdf.erb
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<h1 style="text-align: center;">Reporte de registros</h1>
	<div style="margin-top: 50px; font-size: 18px;">
		<table class="table table-bordered" style="width: 100%">
			<thead>
				<tr style="text-align: center">
					<th>Tipo</th>
					<th>Monto</th>
					<th>Fecha</th>
					<th>Costos adicionales</th>
				</tr>
			</thead>
			<tbody>
				<%@registers.each do |register|%>
				<tr style="text-align: center; margin-top: 100px ">
					<td style="margin-top: 100px;"><%= register.category.name%></td>
					<td class="text-center font-md"><%= register.monto%> $</td>
					<td class="text-center font-md"><%= register.fecha%></td>
					<td class="text-center font-md"><%= register.costos_adicionales%> $</td>
				</tr>
				<%end%>
			</tbody>
		</table>
	</div>	

app/views/registers/show.js.erb
$('<%= j render "show", title: "Ventana" %>').modal();