config/routes.rb
Rails.application.routes.draw do

  resources :tickets
  resources :tic_types
  devise_for :controllers
  namespace :admin do
    resources :users
    resources :categories
    resources :registers

    resources :tickets do
      member do
        patch :change_status
      end
    end

    root to: "users#index"
  end

  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :registers do
    collection do
      match 'search' => 'registers#compare', via: [:get, :post], as: :search
    end
  end
  # resources :registers , only: [:create]

  root 'welcome#index'
  get "/About", to: "welcome#about"
  get "/Contact", to: "welcome#contact"
  get "/Index", to: "welcome#index"
  get "/Compare", to: "registers#compare"
  get "/Console", to: "welcome#console"
  get "/mobile", to: "welcome#mobile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/tic_types_controller.rb
class TicTypesController < ApplicationController
  before_action :set_tic_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @tic_types = TicType.all
  end

  # GET /tic_types/new
  def new
    @tic_type = TicType.new
  end

  # GET /tic_types/1/edit
  def edit
  end

  # POST /tic_types
  # POST /tic_types.json
  def create
    @tic_type = TicType.new(tic_type_params)

    respond_to do |format|
      if @tic_type.save
        format.html { redirect_to @tic_type, notice: 'Tic type was successfully created.' }
        format.json { render :show, status: :created, location: @tic_type }
      else
        format.html { render :new }
        format.json { render json: @tic_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tic_types/1
  # PATCH/PUT /tic_types/1.json
  def update
    respond_to do |format|
      if @tic_type.update(tic_type_params)
        format.html { redirect_to @tic_type, notice: 'Tic type was successfully updated.' }
        format.json { render :show, status: :ok, location: @tic_type }
      else
        format.html { render :edit }
        format.json { render json: @tic_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tic_types/1
  # DELETE /tic_types/1.json
  def destroy
    @tic_type.destroy
    respond_to do |format|
      format.html { redirect_to tic_types_url, notice: 'Tic type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tic_type
      @tic_type = TicType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tic_type_params
      params.require(:tic_type).permit(:name)
    end
end

app/helpers/tic_types_helper.rb
module TicTypesHelper
end

app/views/tic_types/_form.html.erb
<%= simple_form_for(@tic_type) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs space-top-lg">
    <%= f.input :name  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
    <%= link_to 'Atrás', tic_types_path, class: 'btn bg-dark text-white' %>
  </div>
<% end %>

app/views/tic_types/edit.html.erb
<h1>Editing Tic Type</h1>

<%= render 'form', tic_type: @tic_type %>

<%= link_to 'Show', @tic_type %> |
<%= link_to 'Back', tic_types_path %>

app/views/tic_types/index.html.erb
<h2 class="space-top-md">Tipos de tickets</h2>

<table class="table table-hover table-striped table-bordered space-top-md text-center">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @tic_types.each do |tic_type| %>
      <tr>
        <td><%= tic_type.name %></td>
        <td class="btn btn-warning btn-md"><%= link_to 'Edit', edit_tic_type_path(tic_type) %></td>
        <td class="btn btn-danger btn-md"><%= link_to 'Destroy', tic_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Tic Type', new_tic_type_path, class: 'btn btn-success' %>

app/views/tic_types/new.html.erb
<h2>New Tic Type</h2>

<%= render 'form', tic_type: @tic_type %>