config/routes.rb
Rails.application.routes.draw do

  resources :tickets
  resources :tic_types
  devise_for :controllers
  namespace :admin do
    resources :users
    resources :categories
    resources :registers

    resources :tickets do
      member do
        patch :change_status
      end
    end

    root to: "users#index"
  end

  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :registers do
    collection do
      match 'search' => 'registers#compare', via: [:get, :post], as: :search
    end
  end
  # resources :registers , only: [:create]

  root 'welcome#index'
  get "/About", to: "welcome#about"
  get "/Contact", to: "welcome#contact"
  get "/Index", to: "welcome#index"
  get "/Compare", to: "registers#compare"
  get "/Console", to: "welcome#console"
  get "/mobile", to: "welcome#mobile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  has_attached_file :screenshot, styles: { medium: "1280 x 720", thumb: "800x600", small: "600 x 400"}
  validates_attachment_content_type :screenshot, content_type: /\Aimage\/.*\Z/

  belongs_to :tic_type
  belongs_to :user

  validates :title, :description, :status, presence: true
  enum status: [:unsolved, :solved, :pending]
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create]
  before_action :authenticate_admin!, except: [:create]

  def index
    ticket_params = params[:ticket_params] || { status_eq: 0 }
    query = Ticket.search(params[:ticket_params])
    @tickets = query.result
  end

  def change_status
    ticket =  Ticket.find(params[:id])
    ticket.public_send("#{params[:new_status]}!")
    redirect_back fallback_location: admin_tickets_path, notice: 'Estado actualizado satisfactoriamente.'
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = current_user.tickets.new
  end



  # GET /tickets/1/edit
  def edit
  end

  def pqrs
    if current_user
      @tickets = current_user.tickets.unsolved
    end
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render admin_tickets_path, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :status, :screenshot, :tic_type_id, :ticket_params)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    if current_user
      @tickets = current_user.tickets.order(created_at: :desc)
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = current_user.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to tickets_path, notice: 'Ticket was successfully created.' }
        format.json { render tickets_path, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to admin_tickets_path, notice: 'Ticket was successfully updated.' }
        format.json { render admin_tickets_path, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :status, :screenshot, :tic_type_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/tickets/_form.html.erb
<%= simple_form_for(@ticket) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs space-top-lg text-center">
    <div class="row">

      <div class="col-md-12 m-1">
        <%= f.label 'Título' %>
        <%= f.input :title, label: false, input_html: { style: 'width: 40%; margin: 0 auto;' } %>
      </div>

      <div class="col-md-12 m-1">
        <%= f.label 'Descripción' %>
        <%= f.input :description, label: false, input_html: { style: 'width: 40%; margin: 0 auto;' } %>
      </div>

      <div class="col-md-12 m-1">
        <% if ticket.screenshot? %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Ver el screenshot
          </button><br>
          <br>
        <% end %>

        <%= f.label 'Captura' %>
        <%= f.input :screenshot, label: false, as: :file, input_html: { style: 'width: 30%; margin: 0 auto;' } %>
      </div>

      <div class="col-md-12 m-1">
        <%= f.label 'Tipo' %>
        <%= f.association :tic_type, label: false, input_html: { style: 'width: 30%; margin: 0 auto;' } %>
      </div>
    </div>
  </div>
  <div class="form-actions text-center">
    <%= f.button :submit, class: 'btn btn-success' %>
    <%= link_to 'Atrás', tickets_path, class: 'btn bg-dark text-white' %>
  </div>
<% end %>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close-image" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= image_tag ticket.screenshot.url(:thumb), class: 'img-fluid' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tickets/edit.html.erb
<div class="rounded-div pb-4" style="background-color: white; width: 95%; margin: 0 auto;">
  <h1 class="text-center mt-4 p-4">Editar Ticket</h1>

  <%= render 'form', ticket: @ticket %>
</div>

app/views/admin/tickets/index.html.erb
<div class="container space-top-lg p-4 rounded-div" style="background-color: white;">
  <h2 class="space-bot-lg mb-4">Tickets</h2>

  <div class="search-form" style="width: 15%;">
    <%= simple_form_for :ticket_params, url: admin_tickets_path, class:'form-inline' , method: :get do |f|%>
      <%= f.label "Estado"%>
      <%= f.input :status_eq, label: false, style: 'width: 100px;', collection: [["Unsolved", 0], ["Solved", 1], ["Pending", 2]]%>
      <%= f.submit 'Search', class: 'btn btn-primary m-0 mb-5' %>
    <% end %>
  </div>

  <% if @tickets.count > 0 %>
    <div class="container">

      <table class="table text-center" style="background-color: white;">
        <thead class="bg-dark text-white font-weight-bold">
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Screenshot</th>
            <th>Tipo</th>
            <th colspan="3">Acciones</th>
            <th>Administrar</th>
          </tr>
        </thead>

        <tbody>
          <% @tickets.each do |ticket| %>
            <tr>
              <td><%= ticket.title %></td>
              <td><%= ticket.description %></td>
              <td><%= ticket.status %></td>
              <% if ticket.screenshot? %>
                <td>
                  <a data-toggle="modal" data-target="#exampleModal<%= ticket.id%>">
                    Ver el screenshot
                  </a>
                </td>
              <% else %>
              <td> X </td>
              <% end %>
              <td>
                <% if ticket.tic_type %>
                  <%= ticket.tic_type.name %>
                <% else %>
                  X
                <% end %>
              </td>
              <td>
                <%= link_to edit_admin_ticket_path(ticket), class:'no-decoration'  do %>
                  <i class="fa fa-eye "></i>
                  Ver Ticket
                <% end %>
              </td>
              <td>
                <%= link_to edit_admin_ticket_path(ticket), class:'no-decoration' do %>
                  <i class="fa fa-edit"></i>
                    Editar Ticket
                <% end %>
              </td>
              <td>
                <%= link_to ticket, method: :delete, data: { confirm: 'Are you sure?' }, class:'no-decoration' do %>
                  <i class="fa fa-trash"></i>
                  Eliminar Ticket
                <% end %>
              </td>
              <td>
                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size: 12px;">
                  Cambiar estado
                </button>
                <ul class="dropdown-menu p-2" aria-labelledby="dropdownMenuButton">
                  <li class="dropdown-item"> <%= link_to('Change to solved', change_status_admin_ticket_path(ticket, new_status: :solved), :data => { :confirm => '¿Estás seguro?' }, method: :patch) %>  </li>
                  <li class="dropdown-item"> <%= link_to('Change to pending', change_status_admin_ticket_path(ticket, new_status: :pending), :data => { :confirm => '¿Estás seguro?' }, method: :patch) %> </li>
                  <li class="dropdown-item"> <%= link_to('Change to unsolved', change_status_admin_ticket_path(ticket, new_status: :unsolved), :data => { :confirm => '¿Estás seguro?' }, method: :patch) %></li>
                </div>
              </td>

            </tr>
             <div class="modal fade" id="exampleModal<%= ticket.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <%= image_tag ticket.screenshot.url(:thumb), class: 'img-fluid' %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>


        </tbody>
      </table>

    <%= link_to 'Nuevo Ticket', new_ticket_path, class: 'btn btn-success' %>
  </div>

  <% else %>
      <h1 class="text-center m-5">No hay tickets de este tipo <i class="far fa-frown ml-2" style="font-size: 50px;"></i></h1>
  <% end %>
</div>

app/views/admin/tickets/new.html.erb
<h1 class="text-center space-top-md">Nuevo Ticket</h1>

<%= render 'form', ticket: @ticket %>

app/views/admin/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>Screenshot:</strong>
  <%= @ticket.screenshot %>
</p>

<p>
  <strong>Tic type:</strong>
  <%= @ticket.tic_type %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>