config/routes.rb
Rails.application.routes.draw do

  resources :tickets
  resources :tic_types
  devise_for :controllers
  namespace :admin do
    resources :users
    resources :categories
    resources :registers

    resources :tickets do
      member do
        patch :change_status
      end
    end

    root to: "users#index"
  end

  resources :categories
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :registers do
    collection do
      match 'search' => 'registers#compare', via: [:get, :post], as: :search
    end
  end
  # resources :registers , only: [:create]

  root 'welcome#index'
  get "/About", to: "welcome#about"
  get "/Contact", to: "welcome#contact"
  get "/Index", to: "welcome#index"
  get "/Compare", to: "registers#compare"
  get "/Console", to: "welcome#console"
  get "/mobile", to: "welcome#mobile"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
	has_many :registers

	UNRANSACKABLE_ATTRIBUTES = ["color", "updated_at", "created_at", "medida", "id"]

	def self.ransackable_attributes auth_object = nil
		(column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
	end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Category.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Category.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @registers = current_user.registers
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color, :medida)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control form-size" %>
  </div>

  <div class="field form-group">
    <%= form.label :color %>
    <%= form.color_field :color%>
  </div>

  <div class="field form-group">
    <%= form.label :medida %>
    <%= form.text_field :medida, class:"form-control"%>
  </div>

  <div class="actions form-group">
    <%= form.submit "Aceptar", class:"btnColor btn btn-success form-inline " %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category, class:"no-decoration" %> |
<%= link_to 'Back', categories_path, class:"no-decoration" %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorías</h1>

<table class="table table-hover table-bordered space-top">
  <thead>
    <tr class="table-categories">
      <th class="text-center">Name</th>
      <th class="text-center">Color</th>
      <th class="text-center">Medida</th>
      <th colspan="3" class="text-center">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <td class="text-center"><%= category.name %></td>
      <td class="text-center"><%= category.color %></td>
      <td class="text-center"><%= category.medida %></td>
      <td class="text-center"><%= link_to category, class:"no-decoration" do %>
        <i class="fa fa-eye "></i>
        Registros de esta categoría
        <% end %></td>
        <td class="text-center"><%= link_to edit_category_path(category), class:"no-decoration" do%>
          <i class="fa fa-edit"></i>
          Editar
        <%end%></td>
        <td class="text-center"><%= link_to category, method: :delete, class:"no-decoration", data: { confirm: '¿Estás seguro?', } do %>
          <i class="fa fa-trash"></i>
          Eliminar
        <%end%></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nueva categoría', new_category_path, class:"btnColor btn btn-success", style:"" %>

app/views/categories/new.html.erb
<h1>Nueva categoría</h1>

<%= render 'form', category: @category %>

<%= link_to 'Atrás', categories_path, class:"btnColor btn btn-danger btn-md " %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<% if request.original_url === 'http://localhost:3000/categories/1' || request.original_url === 'https://spendoe.herokuapp.com/categories/1' %>
	<%if @registers.where(category_id: 1).count === 0  %>
	<center>
		<h1 id="noRegisters" class="margin-registers-lg"></h1>
	</center>
	<script>
		document.getElementById("noRegisters").innerHTML = "Aún no tienes registros por mostrar";
	</script>
	<%end%>
	<h2 class="text-center space-top-md">Registros de agua</h2>
	<% @registers.where(category_id: 1).each do |register|%>
	<div class="container margin-registers table-responsive">

	<table class="table space-top-xl margin-registers hoverable table-bordered">
		<thead class="info-color black-text">
			<tr>				
				<th class="text-center font-md">Valor</th>
				<th class="text-center font-md">Fecha</th>
				<th class="text-center font-md">Costos adicionales</th>
				<th class="text-center font-md" colspan="3">Acciones</th>
			</tr>
		</thead>
		<tbody>
			<tr>				
				<td class="text-center font-md"><%= register.monto%></td>
				<td class="text-center font-md"><%= register.fecha%></td>
				<td class="text-center font-md"><%= register.costos_adicionales%></td>
				<td class="text-center font-md"><%= link_to register, class:"no-decoration" do %>
					<i class="fa fa-eye "></i>
					Ver registro
					<% end %></td>
					<td class="text-center font-md"><%= link_to edit_register_path(register), class:"no-decoration" do%>
						<i class="fa fa-edit"></i>
						Editar
						<%end%></td>
						<td class="text-center font-md"><%= link_to register, method: :delete, class:"no-decoration", data: { confirm: '¿Estás seguro?', } do %>
							<i class="fa fa-trash"></i>
							Eliminar
							<%end%></td>

						</tr>
						<%end%>
					</tbody>

				</table>

	</div>
	


<%elsif request.original_url === 'http://localhost:3000/categories/2' || request.original_url === 'https://spendoe.herokuapp.com/categories/2'%>
	<%if @registers.where(category_id: 2).count === 0  %>
	<center>
		<h1 id="noRegisters" class="margin-registers-lg"></h1>
	</center>
	<script>
		document.getElementById("noRegisters").innerHTML = "Aún no tienes registros por mostrar";
	</script>
	<%end%>
	<h2 class="text-center space-top-md">Registros de luz</h2>
	<% @registers.where(category_id: 2).each do |register|%>
	<div class="container margin-registers table-responsive">		

	<table class="table space-top-xl margin-registers hoverable table-bordered">
		<thead class="black-text" style="background-color: #eeee7f">
			<tr>			
				<th class="text-center font-md">Valor</th>
				<th class="text-center font-md">Fecha</th>
				<th class="text-center font-md">Costos adicionales</th>
				<th class="text-center font-md" colspan="3">Acciones</th>
			</tr>
		</thead>
		<tbody>
			<tr>				
				<td class="text-center font-md"><%= register.monto%></td>
				<td class="text-center font-md"><%= register.fecha%></td>
				<td class="text-center font-md"><%= register.costos_adicionales%></td>
				<td class="text-center font-md"><%= link_to register, class:"no-decoration" do %>
					<i class="fa fa-eye "></i>
					Ver registro
					<% end %></td>
					<td class="text-center font-md"><%= link_to edit_register_path(register), class:"no-decoration" do%>
						<i class="fa fa-edit"></i>
						Editar
						<%end%></td>
						<td class="text-center font-md"><%= link_to register, method: :delete, class:"no-decoration", data: { confirm: '¿Estás seguro?', } do %>
							<i class="fa fa-trash"></i>
							Eliminar
							<%end%></td>

						</tr>
						<%end%>
					</tbody>

				</table>

	</div>
	</div>


<%elsif request.original_url === 'http://localhost:3000/categories/3' || request.original_url === 'https://spendoe.herokuapp.com/categories/3'%>
	<%if @registers.where(category_id: 3).count === 0  %>
	<center>
		<h1 id="noRegisters" class="margin-registers-lg"></h1>
	</center>
	<script>
		document.getElementById("noRegisters").innerHTML = "Aún no tienes registros por mostrar";
	</script>
	<%end%>
	<% @registers.where(category_id: 3).each do |register|%>
	<div class="container margin-registers table-responsive">
		<table class="table space-top-xl margin-registers hoverable table-bordered">
		<thead class="black-text" style="background-color: #fe855e">
			<tr>			
				<th class="text-center font-md">Valor</th>
				<th class="text-center font-md">Fecha</th>
				<th class="text-center font-md">Costos adicionales</th>
				<th class="text-center font-md" colspan="3">Acciones</th>
			</tr>
		</thead>
		<tbody>
			<tr>				
				<td class="text-center font-md"><%= register.monto%></td>
				<td class="text-center font-md"><%= register.fecha%></td>
				<td class="text-center font-md"><%= register.costos_adicionales%></td>
				<td class="text-center"><%= link_to register, class:"no-decoration" do %>
					<i class="fa fa-eye "></i>
					Ver registro
					<% end %></td>
					<td class="text-center font-md"><%= link_to edit_register_path(register), class:"no-decoration" do%>
						<i class="fa fa-edit"></i>
						Editar
						<%end%></td>
						<td class="text-center font-md"><%= link_to register, method: :delete, class:"no-decoration", data: { confirm: '¿Estás seguro?', } do %>
							<i class="fa fa-trash"></i>
							Eliminar
							<%end%></td>

						</tr>
						<%end%>
					</tbody>

				</table>

	</div>
	</div>


<%elsif request.original_url === 'http://localhost:3000/categories/4' || request.original_url === 'https://spendoe.herokuapp.com/categories/4'%>
	<%if @registers.where(category_id: 4).count === 0  %>
	<center>
		<h1 id="noRegisters" class="margin-registers-lg"></h1>
	</center>
	<script>
		document.getElementById("noRegisters").innerHTML = "Aún no tienes registros por mostrar";
	</script>
	<%end%>
	<% @registers.where(category_id: 4).each do |register|%>
	<div class="container margin-registers table-responsive">
		<table class="table space-top-xl margin-registers hoverable table-bordered">
		<thead class="black-text" style="background-color: #8a8181">
			<tr>			
				<th class="text-center font-md">Valor</th>
				<th class="text-center font-md">Fecha</th>
				<th class="text-center font-md">Costos adicionales</th>
				<th class="text-center font-md" colspan="3">Acciones</th>
			</tr>
		</thead>
		<tbody>
			<tr>				
				<td class="text-center font-md"><%= register.monto%></td>
				<td class="text-center font-md"><%= register.fecha%></td>
				<td class="text-center font-md"><%= register.costos_adicionales%></td>
				<td class="text-center font-md"><%= link_to register, class:"no-decoration" do %>
					<i class="fa fa-eye "></i>
					Ver registro
					<% end %></td>
					<td class="text-center font-md"><%= link_to edit_register_path(register), class:"no-decoration" do%>
						<i class="fa fa-edit"></i>
						Editar
						<%end%></td>
						<td class="text-center font-md"><%= link_to register, method: :delete, class:"no-decoration", data: { confirm: '¿Estás seguro?', } do %>
							<i class="fa fa-trash"></i>
							Eliminar
							<%end%></td>

						</tr>
						<%end%>
					</tbody>

				</table>

	</div>
	</div>

<%end%>